# Configuration for therapy session simulation

# Patient model
patient:
  simulator: "eeyore"
  model: "gpt-4.1-mini"
  temperature: 0.7
  max_attempts: 5
  conversation_type: "verbose"
  
# Therapist model
therapist:
  model: "gpt-4.1-mini"
  temperature: 0.5

eval:
  ptc_classifier:
    model: "gpt-4.1-mini"
    temperature: 0.5
    # model: "hosted_vllm/Qwen/Qwen3-30B-A3B-Thinking-2507"
    # temperature: 0.5
    # api_base: "http://141.142.254.224:9000/v1"