# Patient model
patient:
  simulator: "eeyore"
  model: "hosted_vllm/meta-llama/Llama-3.3-70B-Instruct"
  temperature: 0.7
  max_attempts: 5
  conversation_type: "verbose"
  api_base: "http://141.142.254.222:9000/v1"
  
# Therapist model
therapist:
  model: "hosted_vllm/meta-llama/Llama-3.3-70B-Instruct"
  temperature: 0.5
  api_base: "http://141.142.254.222:9000/v1"
